export default [
  {
    company: 'Ikatech Solutions S.A.S',
    position: 'Desarrollador Frontend',
    startDate: '2023',
    endDate: 'Presente',
    descriptions: [
      'Desarrollé una app móvil interna con integración personalizada de React Native y Botpress para análisis gerenciales.',
      'Optimicé el componente core de la empresa, reduciendo renders innecesarios y duplicación de llamadas a APIs con React Query.',
      'Modularicé componentes para mejorar la legibilidad y el rendimiento general.',
      'Desarrollo y mantenimiento de funcionalidades en los proyectos frontend de la empresa.',
    ],
    technologies: [
      'React',
      'TypeScript',
      'Bootstrap',
      'Zustand',
      'React Query',
      'Redux',
      'Redux-Saga',
    ],
  },
  {
    company: 'Tyche S.R.L',
    position: 'Desarrollador React/React Native',
    startDate: '2022',
    endDate: '2023',
    descriptions: [
      'Desarrollé una landing page para promocionar la aplicación móvil.',
      'Implementé la app de React Native en Next.js para su versión web.',
      'Migré formularios de Formik a React Hook Form, mejorando el rendimiento y la validación.',
      'Reemplacé animaciones y gráficas de Reanimated por Skia para mayor fluidez visual.',
      'Participé en el desarrollo y mantenimiento de la app móvil.',
    ],
    technologies: [
      'React',
      'Next.js',
      'React Native',
      'TypeScript',
      'Reanimated',
      'Skia',
      'Apollo',
      'GraphQL',
      'NestJS',
      'React Hook Form',
      'Shopify restyle',
    ],
  },
  {
    company: 'Corporación Berakah C.A',
    position: 'Desarrollador Full Stack',
    startDate: '2021',
    endDate: '2022',
    descriptions: [
      'Implementé un módulo de gestión de inventario para el área de almacén.',
      'Desarrollé un servidor con Node y Express para leer datos desde una balanza industrial conectada al puerto COM y enviar el peso en tiempo real al sistema mediante WebSocket.',
      'Participé en el desarrollo y mantenimiento del CRM interno de la empresa.',
    ],
    technologies: [
      'Laravel',
      'Blade',
      'PHP',
      'Node.js',
      'Express',
      'Socket.io',
      'Node Serial Port',
      'PostgreSQL',
    ],
  },
];
